application:
  processed-text:
    topic: words.processed
  variables:
    host: https://hipsum.co
    type: hipster-centric
    paras: 1

spring:
  application:
    name: betvictor-processing-application
  web:
    resources:
      add-mappings: false
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
